[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version = "0.0.0"
version_scheme = "semver"
version_provider = "scm"
update_changelog_on_bump = true
changelog_start_rev = "0.0.0"