apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-my-flaskapp
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-my-flaskapp
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:

            - name: MYSQL_HOST
              value: "my-app-mysql.dvir-app.svc.cluster.local"
            - name: MYSQL_USER

              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mysql-username
                  key: username

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mysql-password
                  key: password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mysql-root-password
                  key: password
            - name: MYSQL_DATABASE
              value: "world-of-game"
            - name: MYSQL_PORT
              value: "3306"

